### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by rewted** [TheMadSocrates/archlinux-pkgbuilds#1]
how do u build this?

**Comment by TheMadSocrates** [comment]
See [1]. The AUR has more up to date PKGBUILDs for these packages. Those PKGBUILDs supersede these ones in every possible way. One last bit, please see [2] for how to better ask questions ;)

[1] https://wiki.archlinux.org/title/Makepkg
[2] http://www.catb.org/~esr/faqs/smart-questions.html
